FROM ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y openvpn \
    wget \
    unzip \
    curl \
    sshpass \
    openssh-client \
    python3-pip \
    git \
    apt-transport-https \
    software-properties-common

# https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.5#installation-using-a-binary-archive-file
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
        SELECTED_ARCH="x64"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        SELECTED_ARCH="arm64"; \
    else \
        echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell-7.5.4-linux-${SELECTED_ARCH}.tar.gz  && \
    mkdir -p /opt/microsoft/powershell/7  && \
    tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7  && \
    chmod +x /opt/microsoft/powershell/7/pwsh && \
    ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell-7.5.4-linux-arm64.tar.gz
# https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
#RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
#    dpkg -i packages-microsoft-prod.deb && \
#    rm packages-microsoft-prod.deb && \
#    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y powershell

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# https://developer.hashicorp.com/packer/install#linux
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
        SELECTED_ARCH="amd64"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        SELECTED_ARCH="arm64"; \
    else \
        echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.14.2/packer_1.14.2_linux_${SELECTED_ARCH}.zip && \
    unzip -q packer.zip && rm packer.zip && \
    install -m 0755 packer /usr/bin/packer

WORKDIR /app
