name: Build and publish packer
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.packer'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: Dockerfile.packer
          tags: |
            ${{ github.repository }}-packer:latest
            ${{ github.repository }}-packer:${{ github.sha }}
